/**
 * A carousel with scroll-snap whose dot markers and prev/next buttons are
 * GENERATED BY THE BROWSER — zero JS. ::scroll-button() makes the arrows,
 * ::scroll-marker makes the dots, :target-current highlights the active one.
 */
const SLIDES = [1, 2, 3, 4, 5]

export function CarouselDemo() {
  return (
    // The generated ::scroll-button()s anchor to the scroller's containing block,
    // not the scroller itself — so wrap the carousel in a tight, positioned frame
    // to keep the arrows ON the carousel (otherwise they drift onto the slide's
    // wider grid column, the left one landing under the code).
    <div className="carousel-frame">
      <div className="carousel">
        {SLIDES.map((n) => (
          <div className="carousel-slide" style={{ '--i': n }} key={n}>
            {n}
          </div>
        ))}
      </div>
    </div>
  )
}
