/**
 * A carousel with scroll-snap whose dot markers and prev/next buttons are
 * GENERATED BY THE BROWSER — zero JS. ::scroll-button() makes the arrows,
 * ::scroll-marker makes the dots, :target-current highlights the active one.
 */
const SLIDES = [1, 2, 3, 4, 5]

export function CarouselDemo() {
  return (
    <div className="carousel">
      {SLIDES.map((n) => (
        <div className="carousel-slide" style={{ '--i': n }} key={n}>
          {n}
        </div>
      ))}
    </div>
  )
}
